### ISSUE TITLE
reorder string to get the result as on the screen

### ISSUE THREAD

**Issue by Yuriy1988** [lojjic/bidi-js#3] opened 2022-08-26 13:21 UTC
Hi, need some help, please.
I'm dealing with combined LTR, RTL strings, with digits, symbols, arabic, latin, etc
I'm wondering is it possible to reorder a string value from the `<input dir="rtr">` into a string that is actually displayed in the html element

I mean if I have in input
<img width="356" alt="image" src="https://user-images.githubusercontent.com/16666161/186911774-78380739-82a0-4ae1-b652-9a6a4dce0ceb.png">
the value of the input is 
<img width="136" alt="image" src="https://user-images.githubusercontent.com/16666161/186912056-fc791553-6c47-4201-8b4a-3f9eb777a19b.png">

How can I process the input string value to have a string with characters in an order as I see looking at the input

I tried bidi.getReorderedString method and it works cool for such cases:
<img width="111" alt="image" src="https://user-images.githubusercontent.com/16666161/186912621-24f26980-71bc-4e60-a2b8-f2792e91cc88.png">
in the case above the result of the method is exactly what i expect

but if I have arabic chars, then arabic characters are reversed after calling bidi.getReorderedString

**Comment by tahaabu** [comment] 2022-09-16 07:13
@Yuriy1988 Did you find the solution for this? I'm facing the same problem.

**Comment by Yuriy1988** [comment] 2022-09-16 08:49
@tahaabu 
no :(

**Comment by lojjic** [comment] 2022-09-16 12:58
Would you be able to put together a small HTML+JS test case that reproduces your issue?

**Comment by lojjic** [comment] 2023-05-17 22:07
Going to close this due to lack of info.

My best guess based on the info provided is that `getReorderedString` is working properly, but if you try to render that resulting string in HTML, the browser will also apply the Bidi algorithm natively to the characters, resulting in RTL substrings being re-reversed. In other words, rendering a string in HTML is not a good way to determine the actual order of the characters in the string.

**Closed as not planned by lojjic** 2023-05-17 22:07 UTC
